authors:
  giacomo:
    name: Giacomo Tesio
    display_name: Giacomo
    gravatar: 3daaea0ebce68c00202f395eb796724c
    email: giacomo@tesio.it
    web: http://www.tesio.it
    twitter: giacomo.tesio
    github: Shamar
  marco:
    name: Marco Veglio
    display_name: Marco
    web: http://www.linkedin.com/in/marcoveglio
    github: zhelgadis
